name : Build, Test and Deploy React Application

# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build_test:
 # The type of runner that the job will run on
     runs-on: ubuntu-latest

     strategy:      
       matrix: 
        node-version: [20.x]

     steps: 
     #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with: 
            node-version: ${{ matrix.node-version }}
     
        - name: npm ci, build and test
          run: |
           npm ci
           npm run build --if-present
           npm test

        - name: Setup Pages
          id: pages        
          uses: actions/configure-pages@v3

        - name: Upload artifact        
          uses: actions/upload-pages-artifact@v3        
          with:          
          # Upload entire repository          
            path: build          
            if-no-files-found: error

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}

        - name: Commit build files
          run: |
            git config --global user.email "zahermadi@yahoo.fr"
            git config --global user.name "Zaher Madi"
            git add dist
            git commit -m "ci: add compiled dist before publish" || echo "Nothing to commit"


        - name: build and publish package on NPM 
          run : |
            git config --global user.email "zahermadi@yahoo.fr"
            git config --global user.name "Zaher Madi"
            npm run build-npm
            npm version patch
            npm publish

          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Deploy job  
   deploy:    
    # Deploy to the github-pages environment    
    environment:      
      name: github-pages      
      url: ${{steps.deployment.outputs.page_url}}    
    runs-on: ubuntu-latest
    needs: build_test

    # Grant GITHUB_TOKEN the permissions required to make a page deployment
    permissions:
      pages: write      
      id-token: write

   # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4    

     
